// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
import path from 'path';
import { defineConfig, env } from 'prisma/config';

// Carrega explicitamente o arquivo .env.development da raiz do projeto
dotenv.config({ path: path.resolve(process.cwd(), '.env.development') });

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
